### PR TITLE
Issue78

### PR DESCRIPTION
**Pull request by lpg-tech**
1. The Diagram of Resources is removed.
2.  Added Example for Result ABO Rh weak

### CODE REVIEW

**Comment by ziegm** [comment]
@pjolo @lpg-tech I think Patrick would be the right person to review, what do you think?

**Comment by pjolo** [comment]
@lpg-tech 

There are many changes :) 

What I noticed is that in the example of 4-sepsis, the case study is included. I'm not sure if examples are the right place for such descriptions.

And then I noticed that, for example, in the profile CH LAB Observation Results CBC Panel - Blood by Automated count, Results in sliced component, the system and code for valueQantity is fixed at 10*9/L. Can't the unit also be fixed at 10*9/L? 

On the start page, the link for the changelog is missing.

In general, I have noticed in the changelog that many links point to the develop branch (https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/StructureDefinition-ch-lab-observation-egfr-ckd-epi-2009-male.html). It is not good if links redirect to a branch. If the branch is deleted or if no updates are made for a while, these links will no longer work.

**Comment by lpg-tech** [comment]
There are no new commits between base branch 'develop' and head branch 'issue78', hence this issue can be closed

**Comment by lpg-tech** [comment]
There are no new commits between base branch 'develop' and head branch 'issue78', hence this issue must be closed

**Pull request closed without merging**
